<?php
define(INTERVENTION_PRESTATIONS_TITLE, "Liste des prestations");
define(INTERVENTION_PRESTATIONS_NUM, "#");
define(INTERVENTION_PRESTATIONS_PRESTATIONS, "Prestations");
define(INTERVENTION_PRESTATIONS_TIMER, "Durée par défaut (heure)");
define(INTERVENTION_PRESTATIONS_ACTIONS, "Actions");
define(INTERVENTION_PRESTATIONS_ADD_BUTTON, "Ajouter");
define(INTERVENTION_PRESTATIONS_TAB_PRESTATIONS, "Tableau des prestations");
define(INTERVENTION_PRESTATIONS_EDIT, "Modifier");
define(INTERVENTION_PRESTATIONS_ADD_SUCCESS, "La prestation a bien été ajoutée.");
$page_title = INTERVENTION_PRESTATIONS_TITLE;
?>