<?php
define(INTERVENTION_MATERIELS_TITLE, "Liste des materiels");
define(INTERVENTION_MATERIELS_NUM, "#");
define(INTERVENTION_MATERIELS_MATERIELS, "Matieriels");
define(INTERVENTION_MATERIELS_ACTIONS, "Actions");
define(INTERVENTION_MATERIELS_ADD_BUTTON, "Ajouter");
define(INTERVENTION_MATERIELS_TAB_MATERIELS, "Tableau des materiels");
define(INTERVENTION_MATERIELS_EDIT, "Modifier");
define(INTERVENTION_MATERIELS_ADD_SUCCESS, "La matière a bien été ajoutée.");
$page_title = INTERVENTION_MATERIELS_TITLE;
?>