<?php
define(INTERVENTION_RAPPORTS_TYPES_TITLE, 'Liste des rapports types');
define(INTERVENTION_RAPPORTS_TYPES_RIGHTS_DISPLAY_PAGE, 'Voir et modifier les rapports types');
define(INTERVENTION_RAPPORTS_TYPES_SB_SEE, 'Liste des rapports types types');
define(INTERVENTION_RAPPORTS_TYPES_EDIT, 'Modifier');
define(INTERVENTION_RAPPORTS_TYPES_DELETE, 'Supprimer');
define(INTERVENTION_RAPPORTS_TYPES_TAB_RAPPORTS_TYPES, 'Tableau des rapports types');
define(INTERVENTION_RAPPORTS_TYPES_NUM, '#');
define(INTERVENTION_RAPPORTS_TYPES_TITRE, 'Titre du rapport type');
define(INTERVENTION_RAPPORTS_TYPES_TEXTE, 'Rapport');
define(INTERVENTION_RAPPORTS_TYPES_ACTIONS, 'Actions');
define(INTERVENTION_RAPPORTS_TYPES_ADD_BUTTON, 'Ajouter');
define(INTERVENTION_RAPPORTS_TYPES_ADD_SUCCESS, 'Le rapport type a bien été ajouté !');
define(INTERVENTION_RAPPORTS_TYPES_SUBMIT_BUTTON, 'Valider');
define(INTERVENTION_RAPPORTS_TYPES_CANCEL_BUTTON, 'Annuler');
define(INTERVENTION_RAPPORTS_TYPES_ADD_RAPPORT_TYPE, 'Ajouter un rapport type');
$page_title = INTERVENTION_RAPPORTS_TYPES_TITLE;
?>