<?php
define(STAFFS_TITLE, 'Liste du staff');
define(STAFFS_SB_SEE_STAFFS, 'Liste des employés');
define(STAFFS_RIGHTS_SEE_STAFFS, 'Voir la liste des employés (pour modification et gestion des droits) - Ne pas donner ce droit à n\'importe qui !');
define(STAFFS_STAFFS, 'Les employés');
define(STAFFS_NEW_PASSWORD, 'Nouveau mot de passe');
define(STAFFS_CANCEL_BUTTON, 'Annuler');
define(STAFFS_OK_BUTTON, 'Valider');
define(STAFFS_SAVING_BUTTON, 'Sauvegarde...');
define(STAFFS_ACCOUNT_SETTINGS, 'Paramètres du compte');
define(STAFFS_NAME, 'Nom');
define(STAFFS_PSEUDO, 'Pseudo de connexion');
define(STAFFS_LASTNAME, 'Prénom');
define(STAFFS_EMAIL, 'E-mail');
define(STAFFS_PASSWORD, 'Mot de passe');
define(STAFFS_CHANGE_PASSWORD, 'Changer de mot de passe...');
define(STAFFS_PASSWORD_CHANGED, 'Mot de passe changé');
define(STAFFS_NO_STAFF_WITH_THIS_NUM, 'Aucun employé ne porte ce numéro');
define(STAFFS_NO_STAFF_SELECTED, 'Aucun employé selectionné');
define(STAFFS_SEE, 'Voir l\'employé');
define(STAFFS_MANAGE_RIGHTS, 'Gérer les droits de cet employé');
define(STAFFS_CHANGE, 'Changer');
define(STAFFS_CONNECTIONS, 'Connexions');
define(STAFFS_INTERVENTIONS, 'Interventions');
define(STAFFS_PERSONAL_DETAILS, 'Détails personnels');
define(STAFFS_UPDATE_DETAILS, 'Mettre à jour les informations');
$page_title = STAFFS_TITLE;
?>