<?php
define(INTERVENTION_TITLE, 'Intervention Num %num%');
define(INTERVENTION_SB_INTERVENTIONS, 'Intervention');
define(INTERVENTION_SB_NEW_INTER, 'New Interventon');
define(INTERVENTION_CUSTOMER, 'Customer');
define(INTERVENTION_ADRESS, 'Adress');
define(INTERVENTION_CONTACT, 'contact');
define(INTERVENTION_FIXED_PHONE, 'Phone');
define(INTERVENTION_MOBILE_PHONE, 'Mobile');
define(INTERVENTION_EMAIL, 'Mail');
define(INTERVENTION_NAME, 'Name');
define(INTERVENTION_COMMUNICATE, 'Communicate');
define(INTERVENTION_SMS, 'SMS');
define(INTERVENTION_ENTRY, 'Entries');
define(INTERVENTION_PROJET, 'Project');
define(INTERVENTION_COLOR, 'Color');
?>