<?php
define(INTERVENTION_TITLE, 'Intervention N° %num%');
define(INTERVENTION_NO_INTER_SELECTED, 'Aucune Intervention selectionnée');
define(INTERVENTION_NO_INTER_WITH_THIS_NUM, 'Aucune Intervention ne porte ce numéro');
define(INTERVENTION_SB_INTERVENTIONS, 'Intervention');
define(INTERVENTION_SB_NEW_INTER, 'Nouvelle intervention');
define(INTERVENTION_SB_INTER_ALL, 'Toutes les interventions');
define(INTERVENTION_SB_MATIERES, 'Liste des matières');
define(INTERVENTION_SB_ETAPES, 'Liste des étapes');
define(INTERVENTION_SB_TRAITEMENTS, 'Liste des traitements');
define(INTERVENTION_ACTIONS, 'Actions');
define(INTERVENTION_CUSTOMER, 'Client');
define(INTERVENTION_ADRESS, 'Adresse');
define(INTERVENTION_CONTACT, 'Contact');
define(INTERVENTION_FIXED_PHONE, 'Fixe');
define(INTERVENTION_MOBILE_PHONE, 'Portable');
define(INTERVENTION_EMAIL, 'E-mail');
define(INTERVENTION_NAME, 'Nom');
define(INTERVENTION_COMMUNICATE, 'Communiquer');
define(INTERVENTION_SMS, 'SMS');
define(INTERVENTION_ENTRY, 'Saisie');
define(INTERVENTION_COMMENT, 'Commentaires');
define(INTERVENTION_PROJET, 'Projet');
define(INTERVENTION_COLOR, 'Couleur');
define(INTERVENTION_PROCESSING, 'Taitement');
define(INTERVENTION_STEPS, 'Etapes');
define(INTERVENTION_MODIFY_BUTTON, 'Modifier');
define(INTERVENTION_RIGHTS_CREATE_INTER, 'Créer une intervention');
define(INTERVENTION_RIGHTS_TAKE, 'Prendre en charge une intervention');
define(INTERVENTION_RIGHTS_SEE_INTER, 'Voir une intervention');
define(INTERVENTION_RIGHTS_MATIERES, 'Voir et gérer les matières');
define(INTERVENTION_RIGHTS_ETAPES, 'Voir et gérer les étapes');
define(INTERVENTION_RIGHTS_TRAITEMENTS, 'Voir et gérer les traitements');
define(INTERVENTION_RIGHTS_ALL_INTERVENTION, 'Voir les interventions archivées');
define(INTERVENTION_RIGHTS_DECLOTURE, "Déclôturer une intervention");
define(INTERVENTION_RIGHTS_TCHAT, 'Tchater au sein d\'une intervention');
define(INTERVENTION_A_SOLDER, 'Voir les interventions à solder');
$page_title = INTERVENTION_TITLE;
?>