<?php
   $rights['inter']['1'] = INTERVENTION_RIGHTS_SEE_INTER;
   $rights['inter']['2'] = INTERVENTION_RIGHTS_CREATE_INTER;
   $rights['inter']['3'] = INTERVENTION_RIGHTS_EDIT_INTER;
   $rights['inter']['4'] = INTERVENTION_RIGHTS_ADD_HORAIRES;
   $rights['inter']['5'] = INTERVENTION_RIGHTS_SEE_ALL_SCHEDULES;
   $rights['inter']['7'] = INTERVENTION_RIGHTS_ALL_INTERVENTION;
   $rights['inter']['8'] = INTERVENTION_RIGHTS_DECLOTURE;
   $rights['inter']['9'] = INTERVENTION_RIGHTS_CLOTURE;

?>