<?php
    define(DASH_TITLE, 'Tableau de bord');
    define(DASH_SB_GENERAL, 'Général');
    define(DASH_SB_HOME, 'Accueil');
    define(DASH_SB_MY_INTERVENTIONS, 'Mes interventions');
    define(DASH_MY_INTERVENTIONS, 'Mes interventions');
    define(DASH_INTERVENTIONS_WAITING_CLOSING, 'Interventions en attente de clôture');
    define(DASH_NUM_INTER, '#');
    define(DASH_COLOR, 'Couleur');
    define(DASH_CUSTOMER, 'Client');
    define(DASH_DAYS, 'Jours');
    define(DASH_RIGHTS_SEE_FIRST_PAGE, 'Voir la page d\'acceuil');
    define(DASH_RIGHTS_SEE_STATS, 'Voir les statistiques');
    $page_title = DASH_TITLE;
    
?>