<?php
define(COULEUR_TITLE, 'Les couleurs');
define(COULEUR_SB_STOCK, "Stock");
define(COULEUR_SB_SEE_STOCK, "Voir le stock");
define(COULEUR_SB_SEE, "Voir les couleurs");
define(COULEURS_RIGHTS_DISPLAY_PAGE_COLORS, "Voir les couleurs");
define(COULEURS_RIGHTS_DISPLAY_PAGE_STOCKS, "Voir le stock des couleurs");
define(COULEURS_TAB_COLORS, "Tableau des couleurs");
define(COULEURS_TAB_COLORS_STOCKS, "Tableau du stock des couleurs");
define(COULEURS_NUM, "#");
define(COULEURS_NAME, "Couleur");
define(COULEURS_ACTIONS, "Actions");
define(COULEURS_EDIT, "Modifier");
define(COULEURS_RAL, "Ral");
define(COULEURS_ASPECTS, "Aspects");
define(COULEURS_TAB_ASPECTS, 'Tableau des aspects');
define(COULEURS_ADD_BUTTON, "Ajouter");
define(COULEURS_EDIT_BUTTON, "Modifier");
define(COULEURS_COLOR_ADD_SUCCESS, "La couleur à bien été ajoutée !");
define(COULEURS_ASPECT_ADD_SUCCESS, "L'aspect à bien été ajoutée !");
define(COULEUR_SB_MODIFY_STOCK, "Modifier le stock");
define(COULEURS_RIGHTS_MODIFY_STOCKS, "Modifier les quantités en stock");
$page_title = COULEUR_TITLE;
?>