<?php
define(BL_TITLE, 'Les bons de livraison');
define(BL_SB_BL, 'Bons de livraison');
define(BL_SB_MODIFY_UNITS, 'Modifier les unités');
define(BL_SB_CREATE, 'Créer un BL');
define(BL_SB_BLS, 'Liste des BLs');
define(BL_RIGHTS_MODIFY_UNITS, 'Modifier les unités');  
define(BL_RIGHTS_CREATE_BL, 'Editer des Bons de livraison');
define(BL_ELEMENTS, 'Eléments du BL');
define(BL_TAB_ELEMENTS, 'Tableaux des éléments du bon de livraison');
define(BL_DESCRIPTION, 'Déscription');
define(BL_UNITS, "Unités");
define(BL_QTY, 'Quantité');
define(BL_EDIT, 'Editer');
define(BL_DELETE, 'Supprimer');
define(BL_SUBMIT_BUTTON, "Valider");
define(BL_CANCEL_BUTTON, "Annuler");
define(BL_MODIFY_DIALOG_TITLE, "Modification d'un element");
define(BL_ADD_DIALOG_TITLE, "Ajout d'un element");
define(BL_NO_ELIGIBLE, 'Ce client n\'est pas eligible à la création d\'un BL');
define(BL_LIST_BL, 'Liste des bons de livraison créés');
define(BL_BL, 'Bon de livraison');
define(BL_CUSTOMER, 'Client');
define(BL_ACTIONS, 'Actions');
define(BL_EDIT, 'Editer');
define(BL_INTERS, 'Interventions concernées');
define(BL_DATE, 'Date');
$page_title = BL_TITLE;
?>