<?php
define(RIGHTS_TITLE, 'Gestion des droits de %name%');
define(RIGHTS_SB_RIGHTS_MNGMT, 'Administrer les droits');
define(RIGHTS_CHECK_FOR_APPLY_RIGHTS, 'Cocher les lignes pour appliquer les droits');
define(RIGHTS_MODUL, 'Module');
define(RIGHTS_BUTTON_APPLY, 'Valider les modifications');
define(RIGHTS_RIGHTS_DISPLAY_PAGE, 'Voir la liste des droits affectés à l\'utilisateur (et en permettre la modifcation) - Ne pas donner ce droit à n\'importe qui !');
$page_title = RIGHTS_TITLE;
?>