<?php
   $rights['inter']['1'] = INTERVENTION_RIGHTS_SEE_INTER;
   $rights['inter']['2'] = INTERVENTION_RIGHTS_CREATE_INTER;
   $rights['inter']['3'] = INTERVENTION_RIGHTS_TAKE;
   $rights['inter']['4'] = INTERVENTION_RIGHTS_MATIERES;
   $rights['inter']['5'] = INTERVENTION_RIGHTS_ETAPES;
   $rights['inter']['6'] = INTERVENTION_RIGHTS_TRAITEMENTS;
   $rights['inter']['7'] = INTERVENTION_RIGHTS_ALL_INTERVENTION;
   $rights['inter']['8'] = INTERVENTION_RIGHTS_DECLOTURE;
   $rights['inter']['9'] = INTERVENTION_RIGHTS_TCHAT;
   $rights['inter']['10'] = INTERVENTION_A_SOLDER;

?>