<?php
define(TRANS_TITLE, 'Traduction du site');
define(TRANS_SB_TRANSLATE, "Traduire le site");
define(TRANS_CONSTANTE_NAME, 'Nom de la constante');
define(TRANS_MODUL, 'Module');
define(TRANS_BUTTON_SUBMIT, 'Valider la traduction');
define(TRANSLATE_RIGHTS_TRANSLATE_WEBSITE, 'Traduire le site');
define(TRANSLATE_CHANGE, 'Changer');
define(TRANSLATE_CHOOSE_LANG, 'Choisir sa langue');
define(TRANSLATE_CLOSE, 'Fermer');
define(TRANSLATE_CHOOSE_THIS_LANGUAGE, 'Choisir cette langue');
define(TRANSLATE_CLICK_TO_CHOOSE, 'Cliquer sur Appliquer ici pour choisir cette langue');
define(TRANSLATE_APPLY_CHANGE_LANGUAGE_BUTTON, 'Appliquer');
$page_title = TRANS_TITLE;
?>