<?php
define(INTERVENTION_ANTIVIRUS_TITLE, "Liste des antivirus");
define(INTERVENTION_ANTIVIRUS_NUM, "#");
define(INTERVENTION_ANTIVIRUS_ANTIVIRUS, "antivirus");
define(INTERVENTION_ANTIVIRUS_ACTIONS, "Actions");
define(INTERVENTION_ANTIVIRUS_ADD_BUTTON, "Ajouter");
define(INTERVENTION_ANTIVIRUS_TAB_ANTIVIRUS, "Tableau des antivirus");
define(INTERVENTION_ANTIVIRUS_EDIT, "Modifier");
define(INTERVENTION_ANTIVIRUS_ADD_SUCCESS, "La matière a bien été ajoutée.");
$page_title = INTERVENTION_ANTIVIRUS_TITLE;
?>