<?php
define(INTERVENTION_TITLE, 'Intervention N° %num%');
define(INTERVENTION_NO_INTER_SELECTED, 'Aucune Intervention selectionnée');
define(INTERVENTION_NO_INTER_WITH_THIS_NUM, 'Aucune Intervention ne porte ce numéro');
define(INTERVENTION_SB_INTERVENTIONS, 'Intervention');
define(INTERVENTION_SB_NEW_INTER, 'Nouvelle intervention');
define(INTERVENTION_SB_INTER_ALL, 'Toutes les interventions');
define(INTERVENTION_CHANTIER, 'Chantier');
define(INTERVENTION_RIGHTS_CREATE_INTER, 'Créer une intervention');
define(INTERVENTION_RIGHTS_SEE_INTER, 'Voir une intervention');
define(INTERVENTION_RIGHTS_ALL_INTERVENTION, 'Voir les interventions archivées');
define(INTERVENTION_RIGHTS_DECLOTURE, "Déclôturer une intervention");
define(INTERVENTION_RIGHTS_CLOTURE, "Clôturer une intervention");
define(INTERVENTION_RIGHTS_EDIT_INTER, "Editer les paramètres d'une intervention");
define(INTERVENTION_MODIFY_BUTTON, 'Modifier');
define(INTERVENTION_RIGHTS_ADD_HORAIRES, 'Saisir des horaires');
define(INTERVENTION_RIGHTS_SEE_ALL_SCHEDULES, 'Voir les horaires de tout le monde');

$page_title = INTERVENTION_TITLE;
?>