<?php
define(INTERVENTION_MATIERES_TITLE, "Liste des matières");
define(INTERVENTION_MATIERES_NUM, "#");
define(INTERVENTION_MATIERES_MATIERES, "Matières");
define(INTERVENTION_MATIERES_ACTIONS, "Actions");
define(INTERVENTION_MATIERES_ADD_BUTTON, "Ajouter");
define(INTERVENTION_MATIERES_TAB_MATIERES, "Tableau des matières");
define(INTERVENTION_MATIERES_EDIT, "Modifier");
define(INTERVENTION_MATIERES_ADD_SUCCESS, "La matière a bien été ajoutée.");
$page_title = INTERVENTION_MATIERES_TITLE;
?>