<?php
define(INTERVENTION_ETAPES_TITLE, "Liste des étapes");
define(INTERVENTION_ETAPES_NUM, "#");
define(INTERVENTION_ETAPES_ETAPES, "Etapes");
define(INTERVENTION_ETAPES_ACTIONS, "Actions");
define(INTERVENTION_ETAPES_ADD_BUTTON, "Ajouter");
define(INTERVENTION_ETAPES_TAB_ETAPES, "Tableau des étapes");
define(INTERVENTION_ETAPES_EDIT, "Modifier");
define(INTERVENTION_ETAPES_TIME, "Gestion du temps");
define(INTERVENTION_ETAPES_YES, "Oui");
define(INTERVENTION_ETAPES_NO, "Non");
define(INTERVENTION_ETAPES_ADD_SUCCESS, "L'étape a bien été ajoutée.");
$page_title = INTERVENTION_ETAPES_TITLE;
?>