<?php
define(MODULES_TITLE, 'Modules supplémentaires');
define(MODULES_RIGHTS_DISPLAY_PAGE, 'Activer ou désactiver des modules supplémentaires');
define(MODULES_ACTIVADED_MODULS, 'Liste des modules activés');
define(MODULES_NOT_ACTIVADED_MODULS, 'Modules disponibles');
define(MODULES_PER_MONTH, '/ mois');
define(MODULES_ENABLE_BUTTON, 'Activer');
define(MODULES_DISABLE_BUTTON, 'Désactiver');
define(MODULES_FREE, 'Gratuit');
$page_title = MODULES_TITLE;
?>